// comptime_orm/build.rs – reads Comptime.toml and generates comptime_config.rs.
//
// Looks for Comptime.toml starting from CARGO_MANIFEST_DIR and walking
// up to the workspace root.

use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=../Comptime.toml");
    println!("cargo:rerun-if-changed=Comptime.toml");

    let strategy      = read_schema_strategy();
    let strategy_u8   = strategy_to_u8(&strategy);

    let out_dir  = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let config_code = format!(
        "// Generated by comptime_orm/build.rs from Comptime.toml – do not edit manually.\n\
         // Schema management strategy: {:?}\n\
         pub(crate) const SCHEMA_MANAGEMENT_STRATEGY: u8 = {};\n",
        strategy, strategy_u8,
    );
    let config_path = Path::new(&out_dir).join("comptime_config.rs");
    std::fs::write(&config_path, config_code).expect("Could not write comptime_config.rs");
}

/// Find Comptime.toml by searching from the manifest dir upwards.
fn find_comptime_toml() -> Option<PathBuf> {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")
        .map(PathBuf::from)
        .ok()?;

    // Check in current dir first, then walk up.
    let mut dir = manifest_dir.as_path();
    loop {
        let candidate = dir.join("Comptime.toml");
        if candidate.exists() {
            return Some(candidate);
        }
        dir = dir.parent()?;
    }
}

/// Read `schema-management.strategy` from `Comptime.toml`.
/// Returns `"none"` if the file is absent or the key is missing.
fn read_schema_strategy() -> String {
    let path = match find_comptime_toml() {
        Some(p) => p,
        None    => return "none".to_string(),
    };
    let content = match std::fs::read_to_string(&path) {
        Ok(c)  => c,
        Err(_) => return "none".to_string(),
    };
    let mut in_database = false;
    for line in content.lines() {
        let t = line.trim();
        if t.is_empty() || t.starts_with('#') { continue; }
        if t.starts_with('[') {
            in_database = t == "[database]";
            continue;
        }
        if in_database {
            if let Some(rest) = t.strip_prefix("schema-management.strategy") {
                if let Some(eq_rest) = rest.trim_start().strip_prefix('=') {
                    return eq_rest.trim().trim_matches('"').to_string();
                }
            }
        }
    }
    "none".to_string()
}

/// Map strategy name to its `u8` discriminant.
fn strategy_to_u8(s: &str) -> u8 {
    match s {
        "none"            => 0,
        "validate"        => 1,
        "create"          => 2,
        "drop-and-create" => 3,
        "update"          => 4,
        other => {
            eprintln!("cargo:error=Unknown schema-management.strategy in Comptime.toml: '{}'. \
                       Valid values: none | validate | create | drop-and-create | update", other);
            std::process::exit(1);
        }
    }
}
