// src/router/mod.rs – hybrid router: static phf perfect-hash + fast param matcher.
//
// Architecture (Agents.md §7–9, perfect-hash optimisation):
//
//   Static routes  → per-method phf::Map<&str, usize>  (in .rodata, O(1) lookup)
//     The PHF maps are generated by build.rs at compile time and included here.
//     They map normalised path strings to an index into a `&'static [HandlerFn]`
//     array that is populated once at startup from inventory routes.
//
//   Param routes   → Box<[ParamRoute]>  (flat slice, byte-level prefix matcher)
//     Slash-count pre-filter makes the common "wrong depth" case O(1).
//     Captures are collected into a stack buffer; committed only on full match.
//
// Dispatch flow:
//   1.  PHF per-method lookup        → O(1), fully in .rodata
//   2.  PHF_ALL_STATIC_PATHS check   → O(1) 405 detection
//   3.  Byte-level param route scan  → O(param_routes × depth)
//
// Migration note (Agents.md §16):
//   When `#[comptime]` lands, build.rs → comptime function that generates the
//   same phf maps, and inventory → #[comptime] collection.  Public API unchanged.

pub mod build;

use std::collections::HashMap;

use crate::{
    handler::HandlerFn,
    request::{HttpMethod, Request},
    response::Response,
};

// ── Generated perfect-hash tables (build.rs → OUT_DIR/phf_routes.rs) ─
// Each per-method map: path → index into the corresponding handler array.
// PHF_ALL_STATIC_PATHS: union set of all static paths – used for 405.
include!(concat!(env!("OUT_DIR"), "/phf_routes.rs"));

// ──────────────────────────────────────────────────────────────────────
// Public API types  (kept for OpenAPI / registry / backward compat)
// ──────────────────────────────────────────────────────────────────────

/// A segment in a parsed URL path (conceptual; not on the hot path).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PathSegment {
    Static(&'static str),
    Param(&'static str),
    Root,
}

/// Method → handler pair (used in OpenAPI / registry metadata).
pub struct MethodHandler {
    pub method:  HttpMethod,
    pub handler: HandlerFn,
}

// ──────────────────────────────────────────────────────────────────────
// Internal param-route types
// ──────────────────────────────────────────────────────────────────────

pub(crate) enum SegmentKind {
    Static(Box<str>),
    Param(Box<str>),
}

/// A parameterised route with a byte-level prefix matcher.
///
/// `fill_params` operates exclusively on `path.as_bytes()`.  Captures are
/// accumulated in a stack buffer and committed into `path_params` only on a
/// full match, so no allocation occurs on partial/failed matches.
pub(crate) struct ParamRoute {
    pub(crate) method:               HttpMethod,
    pub(crate) segments:             Box<[SegmentKind]>,
    pub(crate) handler:              HandlerFn,
    /// Pre-computed slash count – cheap O(1) depth pre-filter.
    pub(crate) expected_slash_count: usize,
}

impl ParamRoute {
    pub(crate) fn fill_params(
        &self,
        path: &str,
        params: &mut HashMap<String, String>,
    ) -> bool {
        let bytes = path.as_bytes();

        if count_slashes(bytes) != self.expected_slash_count {
            return false;
        }

        let mut cap_keys: [&str; 8] = [""; 8];
        let mut cap_vals: [&str; 8] = [""; 8];
        let mut cap_count: usize    = 0;

        let mut pos = usize::from(bytes.first() == Some(&b'/'));

        for (i, seg) in self.segments.iter().enumerate() {
            let is_last = i + 1 == self.segments.len();
            let seg_end = if is_last {
                bytes.len()
            } else {
                match find_slash(&bytes[pos..]) {
                    Some(p) => pos + p,
                    None    => return false,
                }
            };

            let chunk = &bytes[pos..seg_end];
            match seg {
                SegmentKind::Static(s) => {
                    if chunk != s.as_bytes() { return false; }
                }
                SegmentKind::Param(name) => {
                    if chunk.is_empty() { return false; }
                    let val = match std::str::from_utf8(chunk) {
                        Ok(v)  => v,
                        Err(_) => return false,
                    };
                    if cap_count < cap_keys.len() {
                        cap_keys[cap_count] = name.as_ref();
                        cap_vals[cap_count] = val;
                        cap_count += 1;
                    }
                }
            }
            pos = seg_end + 1;
        }

        // Full match – commit captures.
        for i in 0..cap_count {
            params.insert(cap_keys[i].to_string(), cap_vals[i].to_string());
        }
        true
    }
}

#[inline]
fn count_slashes(bytes: &[u8]) -> usize {
    bytes.iter().filter(|&&b| b == b'/').count()
}

#[inline]
fn find_slash(bytes: &[u8]) -> Option<usize> {
    bytes.iter().position(|&b| b == b'/')
}

// ──────────────────────────────────────────────────────────────────────
// HybridRouter
// ──────────────────────────────────────────────────────────────────────

/// Hybrid router combining compile-time PHF maps and a runtime param matcher.
///
/// **Static routes**: looked up via per-method `phf::Map<&str, usize>` statics
/// (generated by build.rs, placed in `.rodata` — zero heap allocation, O(1)).
/// The `usize` is an index into the corresponding `&'static [HandlerFn]` slice,
/// which is populated once at startup from inventory and then leaked.
///
/// **Param routes**: stored in a flat `Box<[ParamRoute]>`, matched with a
/// byte-level scanner and a slash-count pre-filter.
pub struct HybridRouter {
    pub(crate) get_handlers:     &'static [HandlerFn],
    pub(crate) post_handlers:    &'static [HandlerFn],
    pub(crate) put_handlers:     &'static [HandlerFn],
    pub(crate) delete_handlers:  &'static [HandlerFn],
    pub(crate) patch_handlers:   &'static [HandlerFn],
    pub(crate) head_handlers:    &'static [HandlerFn],
    pub(crate) options_handlers: &'static [HandlerFn],
    pub(crate) param_routes:     Box<[ParamRoute]>,
}

impl HybridRouter {
    /// Look up a static route.  Uses the phf::Map from `.rodata` (O(1), no alloc).
    #[inline]
    fn lookup_static(&self, method: HttpMethod, path: &str) -> Option<HandlerFn> {
        match method {
            HttpMethod::Get     => PHF_GET_ROUTES.get(path).map(|&i| self.get_handlers[i]),
            HttpMethod::Post    => PHF_POST_ROUTES.get(path).map(|&i| self.post_handlers[i]),
            HttpMethod::Put     => PHF_PUT_ROUTES.get(path).map(|&i| self.put_handlers[i]),
            HttpMethod::Delete  => PHF_DELETE_ROUTES.get(path).map(|&i| self.delete_handlers[i]),
            HttpMethod::Patch   => PHF_PATCH_ROUTES.get(path).map(|&i| self.patch_handlers[i]),
            HttpMethod::Head    => PHF_HEAD_ROUTES.get(path).map(|&i| self.head_handlers[i]),
            HttpMethod::Options => PHF_OPTIONS_ROUTES.get(path).map(|&i| self.options_handlers[i]),
        }
    }
}

// ──────────────────────────────────────────────────────────────────────
// Dispatch  (Agents.md §9)
// ──────────────────────────────────────────────────────────────────────

/// Dispatch an incoming request to the correct handler.
///
/// **Static hot path**: O(1), zero allocations — PHF map lookup into a static
/// handler slice, both resident in `.rodata` / leaked heap.
///
/// **Param path**: O(param_routes × path_depth), one allocation per captured
/// param value (unavoidable — values must live in the `Request`).
pub async fn dispatch(router: &'static HybridRouter, mut req: Request) -> Response {
    // Normalise: strip trailing slash (except bare `/`).
    if req.path.len() > 1 && req.path.ends_with('/') {
        req.path.pop();
    }

    // 1. Per-method PHF map – O(1), fully in .rodata, zero allocation.
    if let Some(handler) = router.lookup_static(req.method, &req.path) {
        return handler(&req).await;
    }

    // 1b. Path found in some other method's static map → 405.
    if PHF_ALL_STATIC_PATHS.contains(req.path.as_str()) {
        return Response::method_not_allowed();
    }

    // 2. Param routes (byte-level prefix scan, slash-count pre-filter).
    for route in router.param_routes.iter() {
        if route.method != req.method {
            continue;
        }
        let matched = {
            let path: &str = &req.path;
            route.fill_params(path, &mut req.path_params)
        };
        if matched {
            return (route.handler)(&req).await;
        }
    }

    Response::not_found()
}
