// comptime_orm/src/entity.rs – compile-time entity metadata and DbEntity trait.
//
// SQL strings are generated by `#[derive(Entity)]` (comptime_orm_macros) at
// compile time and stored as &'static str in .rodata.
//
// Row mapping is delegated to sqlx::FromRow (generated alongside Entity).
//
// Migration note (Agents.md §16):
//   When #[comptime] + full field-level reflection stabilises, the macro is
//   replaced by a comptime fn.  The DbEntity trait and EntityMeta stay identical.

use crate::query::Query;

// ──────────────────────────────────────────────────────────────────────
// SQL type classification
// ──────────────────────────────────────────────────────────────────────

/// SQL column types. Kept small – extend as needed.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SqlType {
    SmallInt,
    Integer,
    BigInt,
    Real,
    DoublePrecision,
    Boolean,
    Text,
    Bytea,
    Json,
    Uuid,
    Timestamp,
    Date,
}

impl SqlType {
    /// The SQL keyword for this type (used in migration DDL).
    pub const fn as_sql_str(self) -> &'static str {
        match self {
            SqlType::SmallInt        => "SMALLINT",
            SqlType::Integer         => "INTEGER",
            SqlType::BigInt          => "BIGINT",
            SqlType::Real            => "REAL",
            SqlType::DoublePrecision => "DOUBLE PRECISION",
            SqlType::Boolean         => "BOOLEAN",
            SqlType::Text            => "TEXT",
            SqlType::Bytea           => "BYTEA",
            SqlType::Json            => "JSON",
            SqlType::Uuid            => "UUID",
            SqlType::Timestamp       => "TIMESTAMP",
            SqlType::Date            => "DATE",
        }
    }
}

// ──────────────────────────────────────────────────────────────────────
// Column metadata
// ──────────────────────────────────────────────────────────────────────

/// Compile-time description of a single database column.
#[derive(Debug, Clone, Copy)]
pub struct ColumnMeta {
    /// SQL column name (snake_case).
    pub name:     &'static str,
    /// SQL data type.
    pub sql_type: SqlType,
    /// Whether the column accepts NULL.
    pub nullable: bool,
    /// Whether this column is (part of) the primary key.
    pub is_pk:    bool,
}

// ──────────────────────────────────────────────────────────────────────
// Entity metadata – one per struct, generated by #[derive(Entity)]
// ──────────────────────────────────────────────────────────────────────

/// All compile-time knowledge about a database entity.
///
/// Assigned to a `static` item by `#[derive(Entity)]`.  Every string field
/// is a `&'static str` computed entirely at compile time.
#[derive(Debug, Clone, Copy)]
pub struct EntityMeta {
    pub table:               &'static str,
    pub columns:             &'static [ColumnMeta],
    pub find_sql:            &'static str,
    pub find_all_sql:        &'static str,
    pub insert_sql:          &'static str,
    pub insert_returning_sql: &'static str,
    pub update_sql:           &'static str,
    pub delete_sql:          &'static str,
    pub migration_sql:       &'static str,
    pub drop_sql:            &'static str,
}

// ──────────────────────────────────────────────────────────────────────
// DbEntity trait
// ──────────────────────────────────────────────────────────────────────

/// Implemented by every struct annotated with `#[derive(Entity)]`.
pub trait DbEntity: Sized {
    fn entity_meta() -> &'static EntityMeta;

    fn query()                -> Query<Self>  { Query::new() }
    fn find_sql()             -> &'static str { Self::entity_meta().find_sql }
    fn find_all_sql()         -> &'static str { Self::entity_meta().find_all_sql }
    fn insert_sql()           -> &'static str { Self::entity_meta().insert_sql }
    fn insert_returning_sql() -> &'static str { Self::entity_meta().insert_returning_sql }
    fn update_sql()           -> &'static str { Self::entity_meta().update_sql }
    fn delete_sql()           -> &'static str { Self::entity_meta().delete_sql }
    fn migration_sql()        -> &'static str { Self::entity_meta().migration_sql }
    fn drop_sql()             -> &'static str { Self::entity_meta().drop_sql }
}

// ──────────────────────────────────────────────────────────────────────
// Entity registry (inventory-based collection)
// ──────────────────────────────────────────────────────────────────────

/// Wrapper submitted via `inventory::submit!` by each `#[derive(Entity)]` expansion.
pub struct EntityRegistration {
    pub meta: &'static EntityMeta,
}

inventory::collect!(EntityRegistration);

/// Iterate over every entity registered through `inventory::submit!`.
pub fn all_entities() -> impl Iterator<Item = &'static EntityRegistration> {
    inventory::iter::<EntityRegistration>()
}
